# Generated by Django 4.1.dev20211001111137 on 2021-10-07 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_mail_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
